//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Basic.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebSiteBanHangEntities : DbContext
    {
        public WebSiteBanHangEntities()
            : base("name=WebSiteBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Brand_2119110143> Brand_2119110143 { get; set; }
        public DbSet<Category_2119110143> Category_2119110143 { get; set; }
        public DbSet<Product_2119110143> Product_2119110143 { get; set; }
        public DbSet<User_2119110143> User_2119110143 { get; set; }
        public DbSet<OrderDetail_2119110143> OrderDetail_2119110143 { get; set; }
        public DbSet<Order_2119110143> Order_2119110143 { get; set; }
    }
}
