//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Basic.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_2119110143
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
    }
}
